StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5EA73DBF40044FB3}" {
   Id "PS-Keybind_Comms_Playable_Selector"
   Target_en_us "Team switch"
   Target_ru_ru "Смена роли"
   Modified 1588028307
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932C446D469ED}" {
   Id "PS-Keybind_CommsOpenLobby"
   Target_en_us "Open lobby"
   Target_ru_ru "Открыть лобби"
   Modified 1588200867
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941A166E74B}" {
   Id "PS-Lobby_Chat"
   Target_en_us "Chat"
   Target_ru_ru "Чат"
   Modified 1588026348
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941A71E17E8}" {
   Id "PS-Lobby_CloseLobby"
   Target_en_us "Leave game"
   Target_ru_ru "Покинуть игру"
   Modified 1588026309
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF442B2167}" {
   Id "PS-Lobby_Factions"
   Target_en_us "Factions"
   Target_ru_ru "Фракции"
   Modified 1588025331
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932EC5F220341}" {
   Id "PS-Lobby_ForceStart"
   Target_en_us "Start game"
   Target_ru_ru "Начать игру"
   Modified 1588355597
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932EA0659A8C5}" {
   Id "PS-Lobby_Join"
   Target_en_us "Join game"
   Target_ru_ru "Вступить в игру"
   Modified 1588149476
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932E9950F27EF}" {
   Id "PS-Lobby_JoinAsObserver"
   Target_en_us "Spectate"
   Target_ru_ru "Наблюдать"
   Modified 1588150413
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF46DC78AF}" {
   Id "PS-Lobby_LoadoutPreview"
   Target_en_us "Loadout Preview"
   Target_ru_ru "Предпросмотр"
   Modified 1588025334
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF798A6D5B}" {
   Id "PS-Lobby_Players"
   Target_en_us "Players"
   Target_ru_ru "Игроки"
   Modified 1588025336
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941AE8846DA}" {
   Id "PS-Lobby_Ready"
   Target_en_us "Ready"
   Target_ru_ru "Готов"
   Modified 1588026052
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF7D6EDF21}" {
   Id "PS-Lobby_Roles"
   Target_en_us "Roles"
   Target_ru_ru "Роли"
   Modified 1588025338
   Author "SeskPC"
   LastChanged "SeskPC"
  }
 }
}