StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5EC5311E4F6DC81D}" {
   Id "PS-Briefing_GroupVoiceChat"
   Target_en_us "Group сhat"
   Target_ru_ru "Отрядный чат"
   Modified 1589982424
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E46366D61D92}" {
   Id "PS-Briefing_MissionDescriptionHeader"
   Target_en_us "Mission description"
   Target_ru_ru "Описание сценария"
   Modified 1589838722
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47F1F2FA6D1}" {
   Id "PS-Briefing_MissionDescriptionHide"
   Target_en_us "Hide mission description"
   Target_ru_ru "Скрыть описание миссии"
   Modified 1589838171
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47F0691875D}" {
   Id "PS-Briefing_MissionDescriptionShow"
   Target_en_us "Show mission description"
   Target_ru_ru "Показать описание миссии"
   Modified 1589838147
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AFCF3D60D9339}" {
   Id "PS-Briefing_PlayableNotSelected"
   Target_en_us "Role are not selected!"\
   "On mission start you will become a spectator!"
   Target_ru_ru "Роль не выбрана!"\
   "На старте миссии вы станете наблюдателем!"
   Modified 1594565604
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AFCF3B4D7E97D}" {
   Id "PS-Briefing_Steps"
   Modified 1594564298
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC5311E7A654D14}" {
   Id "PS-Briefing_VoiceChat"
   Target_en_us "Voice chat"
   Target_ru_ru "Голосовой чат"
   Modified 1589982033
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47F1C0F3895}" {
   Id "PS-Briefing_VoiceChatHide"
   Target_en_us "Hide voice chat"
   Target_ru_ru "Скрыть голосовой чат"
   Modified 1589838065
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47F00BC0D4E}" {
   Id "PS-Briefing_VoiceChatShow"
   Target_en_us "Show voice chat"
   Target_ru_ru "Показать голосовой чат"
   Modified 1589837352
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E474747EACEA}" {
   Id "PS-Debrief_Losses"
   Target_en_us "Faction statistic"
   Target_ru_ru "Фракционная статистика"
   Modified 1589835442
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E4747D62E00C}" {
   Id "PS-Debrief_Objectives"
   Target_en_us "Objectives"
   Target_ru_ru "Задачи"
   Modified 1589835414
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54DBE99E97}" {
   Id "PS-Description_HeaderAboutMission"
   Target_en_us "General information"
   Target_ru_ru "Общая информация"
   Modified 1589836648
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54EAA8176D}" {
   Id "PS-Description_HeaderFIA"
   Target_en_us "FIA objectives"
   Target_ru_ru "Задачи FIA"
   Modified 1589836392
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54DD5C222E}" {
   Id "PS-Description_HeaderObjectives"
   Target_en_us "Objectives"
   Target_ru_ru "Задачи"
   Modified 1589836531
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54E131620A}" {
   Id "PS-Description_HeaderRules"
   Target_en_us "Rules"
   Target_ru_ru "Правила"
   Modified 1589836354
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54ED9CAFBA}" {
   Id "PS-Description_HeaderUS"
   Target_en_us "US Army objectives"
   Target_ru_ru "Задачи Армии США"
   Modified 1589836319
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54F35F3D06}" {
   Id "PS-Description_HeaderUSSR"
   Target_en_us "Soviet Army objectives"
   Target_ru_ru "Задачи Советской Армии"
   Modified 1589836270
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF96208D034F2DA}" {
   Id "PS-EditorAttribute_GameModeCoop_CanOpenLobbyInLobby"
   Target_en_us "Team Switch"
   Target_ru_ru "Смена роли"
   Modified 1594561447
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF96208D5FE09A6}" {
   Id "PS-EditorAttribute_GameModeCoop_CanOpenLobbyInLobby_Description"
   Target_en_us "Any player will be able to access the lobby during a mission and change role"
   Target_ru_ru "Любой игрок сможет получить доступ в лобби во время миссии и сменить роль"
   Modified 1594563935
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AED380F307AC1}" {
   Id "PS-EditorAttribute_GameModeCoop_DisableLeaderSquadMarkers"
   Target_en_us "Disable squad leader markers"
   Target_ru_ru "Отключить маркера лидеров отрядов"
   Modified 1594563714
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AED38124D830C}" {
   Id "PS-EditorAttribute_GameModeCoop_DisableLeaderSquadMarkers_Description"
   Target_en_us "Squad leaders markers will not appear on the map."
   Target_ru_ru "Маркера лидеров отделений не будут отображены на карте"
   Modified 1594563814
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B44BDD42D}" {
   Id "PS-EditorAttribute_GameModeCoop_FreezeTime"
   Target_en_us "Freeze time"
   Target_ru_ru "Фризтайм"
   Modified 1594561039
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B4932D858}" {
   Id "PS-EditorAttribute_GameModeCoop_FreezeTime_Description"
   Target_en_us "Time from mission start to removal of containment zones"
   Target_ru_ru "Время со старта миссии до удаления зон ограничения"
   Modified 1594563674
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B03413635}" {
   Id "PS-EditorAttribute_GameModeCoop_ReconnectTime"
   Target_en_us "Reconnect time"
   Target_ru_ru "Время для переподключения"
   Modified 1594561032
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B07CEB34C}" {
   Id "PS-EditorAttribute_GameModeCoop_ReconnectTime_Description"
   Target_en_us "Player role reservation time for reconnection"
   Target_ru_ru "Время резервации роли игрока для переподключения"
   Modified 1594563528
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B1D5BEAA7}" {
   Id "PS-EditorAttribute_GameModeCoop_RemoveRedundantUnits"
   Target_en_us "Remove redundant units"
   Target_ru_ru "Удалить незанятых персонажей"
   Modified 1594560608
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B20207DC0}" {
   Id "PS-EditorAttribute_GameModeCoop_RemoveRedundantUnits_Description"
   Target_en_us "Delete not used playable units on mission start"
   Target_ru_ru "Удалить незанятых персонажей на старте миссии"
   Modified 1594563397
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AED380A4931C1}" {
   Id "PS-EditorAttribute_GameModeCoop_ShowMarkersOnlyOnBriefing"
   Target_en_us "Markers only on briefing by squad leaders"
   Target_ru_ru "Маркеры только на брифинге лидерами отрядов"
   Modified 1594565539
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AED380D9701A9}" {
   Id "PS-EditorAttribute_GameModeCoop_ShowMarkersOnlyOnBriefing_Description"
   Target_en_us "Prevents players from placing markers after the briefing and also if they are not the leader of the squad"
   Target_ru_ru "Запрещает игрокам ставить маркера после брифинга а также если они не лидеры отряда"
   Modified 1594563189
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B995D2494}" {
   Id "PS-EditorAttribute_MissionDescription_FactionEmpty"
   Target_en_us "Show to empty faction"
   Target_ru_ru "Показать пустой фракции"
   Modified 1594560563
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B9D907696}" {
   Id "PS-EditorAttribute_MissionDescription_FactionEmpty_Description"
   Target_en_us "Will be this description shown on Mission Preview"
   Target_ru_ru "Будет ли описание доступно на этапе предпросмотра"
   Modified 1594562765
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620BEE5A72E9}" {
   Id "PS-EditorAttribute_MissionDescription_Factions"
   Target_en_us "Show to factions"
   Target_ru_ru "Показать фракциям"
   Modified 1594560552
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620BF214E3D0}" {
   Id "PS-EditorAttribute_MissionDescription_Factions_Description"
   Target_en_us "This description will be shown to selected factions"
   Target_ru_ru "Это описание будет доступно выбранным фракциям"
   Modified 1594562314
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620BCDCE1FDF}" {
   Id "PS-EditorAttribute_MissionDescription_TextData"
   Target_en_us "Text data"
   Target_ru_ru "Текст"
   Modified 1594560539
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620BD39D1418}" {
   Id "PS-EditorAttribute_MissionDescription_TextData_Description"
   Target_en_us "Description tab text"
   Target_ru_ru "Текст в вкладке описания"
   Modified 1594562258
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620A25565F4F}" {
   Id "PS-EditorAttribute_MissionDescription_Title"
   Target_en_us "Title"
   Target_ru_ru "Заголовок"
   Modified 1594560531
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620A2941F17B}" {
   Id "PS-EditorAttribute_MissionDescription_Title_Description"
   Target_en_us "Tab title with mission description"
   Target_ru_ru "Заголовок вкладки с описанием миссии"
   Modified 1594562204
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AF03B543FAF6A}" {
   Id "PS-EditorAttribute_Playable_IsPlayable"
   Target_en_us "Is playable"
   Target_ru_ru "Играбельный"
   Modified 1594560199
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AF03B5602B638}" {
   Id "PS-EditorAttribute_Playable_IsPlayable_Description"
   Target_en_us "Players can play as this unit/squad"
   Target_ru_ru "Игроки смогут играть за этого персонажа/группу"
   Modified 1594562116
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620A4444DA9C}" {
   Id "PS-EditorCategory_Lobby"
   Target_en_us "Reforger Lobby"
   Target_ru_ru "Рефоргер Лобби"
   Modified 1594560073
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF962097FA8C778}" {
   Id "PS-EditorEntity_MissionDescription_Name"
   Target_en_us "Mission description"
   Target_ru_ru "Описание миссии"
   Modified 1594559969
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB30CD4368261A7}" {
   Id "PS-GameMaster_PlayableGroup"
   Target_en_us "Playable Unit"
   Target_ru_ru "Играбельный чел"
   Modified 1589834979
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE506E004252}" {
   Id "PS-GameModeHeader_Advance"
   Target_en_us "Advance"
   Target_ru_ru "Далее"
   Modified 1589052626
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE5226347A67}" {
   Id "PS-GameModeHeader_Briefing"
   Target_en_us "Briefing"
   Target_ru_ru "Инструктаж"
   Modified 1589051957
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE52166ABC2A}" {
   Id "PS-GameModeHeader_Debriefing"
   Target_en_us "Debriefing"
   Target_ru_ru "Итоги"
   Modified 1589051905
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE523BA20242}" {
   Id "PS-GameModeHeader_InGame"
   Target_en_us "Game"
   Target_ru_ru "Игра"
   Modified 1589054432
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE5256808E8E}" {
   Id "PS-GameModeHeader_Lobby"
   Target_en_us "Lobby"
   Target_ru_ru "Лобби"
   Modified 1589051783
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE52778D1F25}" {
   Id "PS-GameModeHeader_Preview"
   Target_en_us "Mission Preview"
   Target_ru_ru "Предпросмотр"
   Modified 1589052651
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF40044FB3}" {
   Id "PS-Keybind_Comms_Playable_Selector"
   Target_en_us "Team switch"
   Target_ru_ru "Смена роли"
   Modified 1588028307
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932C446D469ED}" {
   Id "PS-Keybind_CommsOpenLobby"
   Target_en_us "Open lobby"
   Target_ru_ru "Открыть лобби"
   Modified 1588200867
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47EDD8EAD31}" {
   Id "PS-Keybind_MissionDescriptionSwitch"
   Target_en_us "Mission description interface"
   Target_ru_ru "Интерфейс описания миссии"
   Modified 1589838257
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC5311F4BC93B53}" {
   Id "PS-Keybind_SwitchSpectatorUI"
   Target_en_us "Hide/Show UI"
   Target_ru_ru "Скрыть/Показать UI"
   Modified 1589981655
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47EA1E2244F}" {
   Id "PS-Keybind_VoiceChatSwitch"
   Target_en_us "Voice chat interface"
   Target_ru_ru "Интерфейс голосового чата"
   Modified 1589838225
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941A166E74B}" {
   Id "PS-Lobby_Chat"
   Target_en_us "Chat"
   Target_ru_ru "Чат"
   Modified 1588026348
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF442B2167}" {
   Id "PS-Lobby_Factions"
   Target_en_us "Factions"
   Target_ru_ru "Фракции"
   Modified 1588025331
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932EC5F220341}" {
   Id "PS-Lobby_ForceStart"
   Target_en_us "Start game"
   Target_ru_ru "Начать игру"
   Modified 1588355597
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932EA0659A8C5}" {
   Id "PS-Lobby_Join"
   Target_en_us "Join game"
   Target_ru_ru "Вступить в игру"
   Modified 1588149476
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932E9950F27EF}" {
   Id "PS-Lobby_JoinAsObserver"
   Target_en_us "Spectate"
   Target_ru_ru "Наблюдать"
   Modified 1588150413
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF46DC78AF}" {
   Id "PS-Lobby_LoadoutPreview"
   Target_en_us "Loadout Preview"
   Target_ru_ru "Предпросмотр"
   Modified 1588025334
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EAEBB2F34252729}" {
   Id "PS-Lobby_OpenMenu"
   Target_en_us "Open menu"
   Target_ru_ru "Открыть меню"
   Modified 1588510988
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF798A6D5B}" {
   Id "PS-Lobby_Players"
   Target_en_us "Players"
   Target_ru_ru "Игроки"
   Modified 1588025336
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB753E7EBC5365D}" {
   Id "PS-Lobby_PlayersList"
   Target_en_us "List"
   Target_ru_ru "Список"
   Modified 1589073590
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941AE8846DA}" {
   Id "PS-Lobby_Ready"
   Target_en_us "Ready"
   Target_ru_ru "Готов"
   Modified 1588026052
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF7D6EDF21}" {
   Id "PS-Lobby_Roles"
   Target_en_us "Roles"
   Target_ru_ru "Роли"
   Modified 1588025338
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47913C55F2C}" {
   Id "PS-Lobby_VoiceChat"
   Target_en_us "Voice Chat"
   Target_ru_ru "Голосовой чат"
   Modified 1589835855
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47910530FBD}" {
   Id "PS-Lobby_VoiceChatFaction"
   Target_en_us "Faction voice chat"
   Target_ru_ru "Фракционный голосовой чат"
   Modified 1589854747
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AFCF3DCDE6333}" {
   Id "PS-MissionDescription_Header"
   Modified 1594564254
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EBE323E513FFB52}" {
   Id "PS-ObserverPlayersList"
   Target_en_us "Alive players"
   Target_ru_ru "Живые игроки"
   Modified 1589834974
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EBE323E4409E95B}" {
   Id "PS-Preview_GameStartSoon"
   Target_en_us "Game will start soon"
   Target_ru_ru "Игра скоро начнётся"
   Modified 1589835471
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EBE323E40F74A24}" {
   Id "PS-Preview_PleaseWait"
   Target_en_us "Please wait"
   Target_ru_ru "Пожалуйста подождите"
   Modified 1590240962
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC5311F409ED937}" {
   Id "PS-Spectator_SwitchSpectatorUI"
   Target_en_us "Hide/Show UI"
   Target_ru_ru "Скрыть/Показать UI"
   Modified 1589981769
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC5311F46616798}" {
   Id "PS-Spectator_VoiceChat"
   Target_en_us "Voice Chat"
   Target_ru_ru "Голосовой чат"
   Modified 1589981833
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6E12BC67891C4}" {
   Id "PS-VoNRoom_Command"
   Target_en_us "HQ"
   Target_ru_ru "Штаб"
   Modified 1589044359
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6E12BC05F7F27}" {
   Id "PS-VoNRoom_Faction"
   Target_en_us "Faction"
   Target_ru_ru "Фракция"
   Modified 1589044327
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6E12BF9F8C213}" {
   Id "PS-VoNRoom_Global"
   Target_en_us "Global"
   Target_ru_ru "Глобальный"
   Modified 1589044312
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE5384337A16}" {
   Id "PS-VoNRoom_Header"
   Target_en_us "Voice сhannels"
   Target_ru_ru "Голосовые каналы"
   Modified 1589830923
   Author "SeskPC"
   LastChanged "SeskPC"
  }
 }
}