StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{61B503ED7CAC5E13}" {
   Id "PS-Briefing_FactionsReady"
   Target_en_us "Factions ready"
   Target_fr_fr "Factions prêtes"
   Target_es_es "Preparación de la facción"
   Target_pl_pl "Gotowość frakcji"
   Target_ru_ru "Готовность фракций"
   Target_pt_br "Prontidão da facção"
   Target_uk_ua "Готовність фракцій"
   Modified 1642795307
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC5311E4F6DC81D}" {
   Id "PS-Briefing_GroupVoiceChat"
   Target_en_us "Group сhat"
   Target_fr_fr "Discussion de groupe"
   Target_es_es "Chat de Grupo"
   Target_pl_pl "Czat grupowy"
   Target_ru_ru "Отрядный чат"
   Target_pt_br "Group сhat"
   Target_uk_ua "Чат загону"
   Modified 1642793240
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E46366D61D92}" {
   Id "PS-Briefing_MissionDescriptionHeader"
   Target_en_us "Mission description"
   Target_fr_fr "Descriptif de mission"
   Target_es_es "Descripcion de mision"
   Target_pl_pl "Opis misji"
   Target_ru_ru "Описание сценария"
   Target_pt_br "Descrição da Missão"
   Target_uk_ua "Опис сценарію"
   Modified 1642793262
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47F1F2FA6D1}" {
   Id "PS-Briefing_MissionDescriptionHide"
   Target_en_us "Hide mission description"
   Target_fr_fr "Masquer la description de la mission"
   Target_es_es "Ocultar descripcion de mision"
   Target_pl_pl "Schowaj opis misji"
   Target_ru_ru "Скрыть описание миссии"
   Target_pt_br "Ocultar descrição da missão"
   Target_uk_ua "Сховати опис місії"
   Modified 1642793273
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47F0691875D}" {
   Id "PS-Briefing_MissionDescriptionShow"
   Target_en_us "Show mission description"
   Target_fr_fr "Afficher la description de la mission"
   Target_es_es "Mostrar descripcion de mision"
   Target_pl_pl "Pokaż opis misji"
   Target_ru_ru "Показать описание миссии"
   Target_pt_br "Mostrar descrição da missão"
   Target_uk_ua "Показати опис місії"
   Modified 1642793288
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AFCF3D60D9339}" {
   Id "PS-Briefing_PlayableNotSelected"
   Target_en_us "Role are not selected!"\
   "On mission start you will become a spectator!"
   Target_fr_fr "Les rôles ne sont pas sélectionnés!"\
   "Au début de la mission, vous deviendrez spectateur !"
   Target_es_es "No has seleccionado rol!"\
   "Comenzaras la mision como espectador!"
   Target_pl_pl "Rola nie jest wybrana! Na starcie misji zostaniesz widzem!"
   Target_ru_ru "Роль не выбрана!"\
   "На старте миссии вы станете наблюдателем!"
   Target_pt_br "A função não está selecionada!"\
   "No início da missão você se tornará um espectador!"
   Target_uk_ua "Роль не обрано!"\
   "На старті місії ви станете спостерігачем!"
   Modified 1642793312
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AFCF3B4D7E97D}" {
   Id "PS-Briefing_Steps"
   Target_en_us "Steps"
   Target_fr_fr "Steps"
   Target_es_es "Pasos a seguir"
   Target_pl_pl "Etapy"
   Target_ru_ru "Этапы"
   Target_pt_br "Etapas do briefing"
   Target_uk_ua "Етапи"
   Modified 1642795331
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC5311E7A654D14}" {
   Id "PS-Briefing_VoiceChat"
   Target_en_us "Voice chat"
   Target_fr_fr "Chat vocal"
   Target_es_es "Chat de voz"
   Target_pl_pl "Czat głosowy"
   Target_ru_ru "Голосовой чат"
   Target_pt_br "Chat de voz"
   Target_uk_ua " Голосовий чат"
   Modified 1642793322
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47F1C0F3895}" {
   Id "PS-Briefing_VoiceChatHide"
   Target_en_us "Hide voice chat"
   Target_fr_fr "Masquer le chat vocal"
   Target_es_es "Ocultar chat de voz"
   Target_pl_pl "Schowaj czat głosowy"
   Target_ru_ru "Скрыть голосовой чат"
   Target_pt_br "Ocultar chat de voz"
   Target_uk_ua "Сховати голосовий чат"
   Modified 1642793329
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47F00BC0D4E}" {
   Id "PS-Briefing_VoiceChatShow"
   Target_en_us "Show voice chat"
   Target_fr_fr "Afficher le chat vocal"
   Target_es_es "Mostrar chat de voz"
   Target_pl_pl "Pokaż czat głosowy"
   Target_ru_ru "Показать голосовой чат"
   Target_pt_br "Mostrar chat de voz"
   Target_uk_ua "Показати голосовий чат"
   Modified 1642793332
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0F44E18237239B}" {
   Id "PS-Briefing_YourPlace"
   Target_en_us "Start position"
   Target_fr_fr "Position de départ"
   Target_es_es "Posición de salida"
   Target_pl_pl "Pozycja startowa"
   Target_ru_ru "Стартовая позиция"
   Target_pt_br "Posição de Inicio"
   Target_uk_ua "Стартова позиція"
   Modified 1642793338
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{616ED424FF1D1ABC}" {
   Id "PS-Debrief_AfterAction"
   Target_en_us "After Action Report"
   Target_fr_fr "Rapport après action"
   Target_pl_pl "Raport po akcji"
   Target_ru_ru "Отчет о результатах"
   Modified 1642793389
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E474747EACEA}" {
   Id "PS-Debrief_Losses"
   Target_en_us "Faction statistic"
   Target_fr_fr "Statistiques de la faction"
   Target_es_es "Estadisticas de bando"
   Target_pl_pl "Statystyki fakcji"
   Target_ru_ru "Статистика фракции"
   Target_pt_br "Estatística da facção"
   Target_uk_ua "Статистика фракції"
   Modified 1642793403
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E4747D62E00C}" {
   Id "PS-Debrief_Objectives"
   Target_en_us "Objectives"
   Target_fr_fr "Objectifs"
   Target_es_es "Objectivos"
   Target_pl_pl "Zadania"
   Target_ru_ru "Задачи"
   Target_pt_br "Objetivos"
   Target_uk_ua "Завдання"
   Modified 1642793413
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54DBE99E97}" {
   Id "PS-Description_HeaderAboutMission"
   Target_en_us "General information"
   Target_fr_fr "Informations générales"
   Target_es_es "Informacion general"
   Target_pl_pl "Generalne informacje"
   Target_ru_ru "Общая информация"
   Target_pt_br "Informaçoes Gerais"
   Target_uk_ua "Загальна інформація"
   Modified 1642793423
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54EAA8176D}" {
   Id "PS-Description_HeaderFIA"
   Target_en_us "FIA objectives"
   Target_fr_fr "Objectifs FIA"
   Target_es_es "Objetivos FIA"
   Target_pl_pl "Zadania FIA"
   Target_ru_ru "Задачи FIA"
   Target_pt_br "Objetivos FIA"
   Target_uk_ua "Завдання FIA"
   Modified 1642793429
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54DD5C222E}" {
   Id "PS-Description_HeaderObjectives"
   Target_en_us "Objectives"
   Target_fr_fr "Objectifs"
   Target_es_es "Objectivos"
   Target_pl_pl "Zadania"
   Target_ru_ru "Задачи"
   Target_pt_br "Objetivos"
   Target_uk_ua "Завдання"
   Modified 1642793433
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54E131620A}" {
   Id "PS-Description_HeaderRules"
   Target_en_us "Rules"
   Target_fr_fr "Règles"
   Target_es_es "Reglas"
   Target_pl_pl "Zasady"
   Target_ru_ru "Правила"
   Target_pt_br "Regras"
   Target_uk_ua "Правила"
   Modified 1642793439
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54ED9CAFBA}" {
   Id "PS-Description_HeaderUS"
   Target_en_us "US Army objectives"
   Target_fr_fr "Objectifs US Army"
   Target_es_es "Objetivos US Army"
   Target_pl_pl "Zadania Armii USA"
   Target_ru_ru "Задачи Армии США"
   Target_pt_br "Objetivo Exercito americano"
   Target_uk_ua "Завдання Армії США"
   Modified 1642793445
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC27C54F35F3D06}" {
   Id "PS-Description_HeaderUSSR"
   Target_en_us "Soviet Army objectives"
   Target_fr_fr "Objectifs Soviet Army"
   Target_es_es "Objetivos Sovieticos"
   Target_pl_pl "Zadania Armi Sowieckiej"
   Target_ru_ru "Задачи Советской Армии"
   Target_pt_br "Objetivo Exercito Soviético"
   Target_uk_ua "Завдання Радянської Армії"
   Modified 1642793452
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF96208D034F2DA}" {
   Id "PS-EditorAttribute_GameModeCoop_CanOpenLobbyInLobby"
   Target_en_us "Team Switch"
   Target_fr_fr "Changement d'équipe"
   Target_es_es "Cambio de bando"
   Target_pl_pl "Zmiana drużyn"
   Target_ru_ru "Смена роли"
   Target_pt_br "Troca de Times"
   Target_uk_ua "Зміна ролі"
   Modified 1642793475
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF96208D5FE09A6}" {
   Id "PS-EditorAttribute_GameModeCoop_CanOpenLobbyInLobby_Description"
   Target_en_us "Any player will be able to access the lobby during a mission and change role"
   Target_fr_fr "N'importe quel joueur pourra accéder au lobby pendant une mission et changer de rôle"
   Target_es_es "Cualquier jugador tiene acceso al lobby durante la partida"
   Target_pl_pl "Jakikolwiek gracz będzie mógł uzyskać dostęp do lobby podczas misji i zmienić rolę"\
   ""
   Target_ru_ru "Любой игрок сможет получить доступ в лобби во время миссии и сменить роль"
   Target_pt_br "Qualquer jogador poderá acessar o lobby durante uma missão e mudar de função"
   Target_uk_ua "Будь-який гравець зможе отримати доступ до лобі під час місії та змінити роль"
   Modified 1642793491
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AED380F307AC1}" {
   Id "PS-EditorAttribute_GameModeCoop_DisableLeaderSquadMarkers"
   Target_en_us "Disable squad leader markers"
   Target_fr_fr "Désactiver les marqueurs de chef d'escouade"
   Target_es_es "Deshabilita marcas de lideres de escuadras"
   Target_pl_pl "Wyłącz markery dowódców oddziałów"
   Target_ru_ru "Отключить маркера лидеров отрядов"
   Target_pt_br "Desativar marcadores de líder de esquadrão"
   Target_uk_ua "Вимкнути маркери лідерів загонів"
   Modified 1642793501
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AED38124D830C}" {
   Id "PS-EditorAttribute_GameModeCoop_DisableLeaderSquadMarkers_Description"
   Target_en_us "Squad leaders markers will not appear on the map."
   Target_fr_fr "Les marqueurs de chefs d’escouade n’apparaîtront pas sur la carte."
   Target_es_es "Las marcas de lideres de escuadra no apareceran en el mapa"
   Target_pl_pl "Markery dowódców oddziałów nie będą pokazane na mapie"
   Target_ru_ru "Маркеры лидеров отрядов не будут отображены на карте"
   Target_pt_br "Marcaçoes de lideres de Esquadrao não irao aparecer no mapa"
   Target_uk_ua "Маркери лідерів загонів не будуть відображені на карті"
   Modified 1642793521
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B44BDD42D}" {
   Id "PS-EditorAttribute_GameModeCoop_FreezeTime"
   Target_en_us "Freeze time"
   Target_fr_fr "Délai de freeze"
   Target_es_es "Momentos congelados"
   Target_pl_pl "Zamrożenie czasu"
   Target_ru_ru "Фризтайм"
   Target_pt_br "Tempo de congelamento"
   Target_uk_ua "Фризтайм"
   Modified 1642793530
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B4932D858}" {
   Id "PS-EditorAttribute_GameModeCoop_FreezeTime_Description"
   Target_en_us "Time from mission start to removal of containment zones"
   Target_fr_fr "Délai entre le début de la mission et la suppression des zones de confinement"
   Target_es_es "Tiempo para quitar las zonas de retencion"
   Target_pl_pl "Czas od startu misji do usunięcia stref powstrzymujących"
   Target_ru_ru "Время со старта миссии до удаления зон ограничения"
   Target_pt_br "Tempo desde o início da missão até a remoção das zonas de contenção"
   Target_uk_ua "Час зі старту місії до видалення зон обмеження"
   Modified 1642793547
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B03413635}" {
   Id "PS-EditorAttribute_GameModeCoop_ReconnectTime"
   Target_en_us "Reconnect time"
   Target_fr_fr "Délai de reconnexion"
   Target_es_es "Tiempo de reconexion"
   Target_pl_pl "Czas na ponowne dołączenie"
   Target_ru_ru "Время для переподключения"
   Target_pt_br "Tempo de reconexão"
   Target_uk_ua "Час для перепідключення"
   Modified 1642793566
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B07CEB34C}" {
   Id "PS-EditorAttribute_GameModeCoop_ReconnectTime_Description"
   Target_en_us "Player role reservation time for reconnection"
   Target_fr_fr "Durée de réservation du rôle du joueur pour la reconnexion"
   Target_es_es "Reserva de tiempo para la reconexion del jugador"
   Target_pl_pl "Czas na ponowne dołącznie na zarezerwowaną role dla gracza"
   Target_ru_ru "Время резервации роли игрока для переподключения"
   Target_pt_br "Tempo de reserva da função do jogador para reconexão"
   Target_uk_ua "Час резервації ролі гравця для перепідключення"
   Modified 1642793575
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B1D5BEAA7}" {
   Id "PS-EditorAttribute_GameModeCoop_RemoveRedundantUnits"
   Target_en_us "Remove redundant units"
   Target_fr_fr "Supprimer les unités redondantes"
   Target_es_es "Borrar unidades redundantes"
   Target_pl_pl "Usuń zbędne jednostki"
   Target_ru_ru "Удалить незанятых персонажей"
   Target_pt_br "Remova unidades redundantes"
   Target_uk_ua "Видалити незайнятих персонажів"
   Modified 1642793580
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B20207DC0}" {
   Id "PS-EditorAttribute_GameModeCoop_RemoveRedundantUnits_Description"
   Target_en_us "Delete not used playable units on mission start"
   Target_fr_fr "Supprimer les unités jouables non utilisées au début de la mission"
   Target_es_es "Borra las unidades jugables sin jugador al comienzo de la partida"
   Target_pl_pl "Usuń nie używane grywalne jednostkii na starcie misji"
   Target_ru_ru "Удалить незанятых персонажей на старте миссии"
   Target_pt_br "Exclua unidades jogáveis não utilizadas no início da missão"
   Target_uk_ua "Видалити незайнятих персонажів на старті місії"
   Modified 1642793799
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AED380A4931C1}" {
   Id "PS-EditorAttribute_GameModeCoop_ShowMarkersOnlyOnBriefing"
   Target_en_us "Map markers can be placed only on briefing by squad leaders"
   Target_fr_fr "Les marqueurs de carte ne peuvent être placés que lors du briefing des chefs d'escouade."
   Target_es_es "Los marcadores en el mapa solo pueden colocarlos los lideres de escuadra"
   Target_pl_pl "Markery na mapie mogą być postawione na sprawozdaniu tylko przez dowódców oddziałów"
   Target_ru_ru "Маркеры на карте могут быть поставлены только на брифинге лидерами отрядов"
   Target_pt_br "Marcaçoes de mapa só podem ser colocados durante instruções dos líderes de esquadrão"
   Target_uk_ua "Маркери на карті можуть бути поставлені тільки на брифінгу лідерами загонів"
   Modified 1642793786
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AED380D9701A9}" {
   Id "PS-EditorAttribute_GameModeCoop_ShowMarkersOnlyOnBriefing_Description"
   Target_en_us "Prevents players from placing markers after the briefing and also if they are not the leader of the squad"
   Target_fr_fr "Empêche les joueurs de placer des marqueurs après le briefing et également s'ils ne sont pas le chef de l'équipe"
   Target_es_es "Evita que los jugadores coloquen marcas despues del briefing si no son lideres de escuadra"
   Target_pl_pl "Zapobiega graczom postawienie markerów po zakończeniu sprawozdania i także jeżeli nie są dowódcami oddziałów"
   Target_ru_ru "Запрещает игрокам ставить маркера после брифинга а также если они не лидеры отряда"
   Target_pt_br "Impede que os jogadores coloquem marcadores após o briefing e também se não forem o líder do Squad"
   Target_uk_ua "Забороняє гравцям ставити маркера після брифінгу а також якщо вони не лідери загону"
   Modified 1642793774
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B995D2494}" {
   Id "PS-EditorAttribute_MissionDescription_FactionEmpty"
   Target_en_us "Show to empty faction"
   Target_fr_fr "Afficher à une faction vide"
   Target_es_es "Mostrar bando vacio"
   Target_pl_pl "Pokaż pustej frakcji"
   Target_ru_ru "Показать пустой фракции"
   Target_pt_br "Mostrar para facção vazia"
   Target_uk_ua "Показати порожній фракції"
   Modified 1642793831
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620B9D907696}" {
   Id "PS-EditorAttribute_MissionDescription_FactionEmpty_Description"
   Target_en_us "Will be this description shown on Mission Preview"
   Target_fr_fr "Cette description sera affichée sur l'aperçu de mission"
   Target_es_es "Se mostrara esta descripcion en la vista previa de la misión"
   Target_pl_pl "Czy ten opis będzie pokazany na podglądzie misji"
   Target_ru_ru "Будет ли описание доступно на этапе предпросмотра"
   Target_pt_br "Esta descrição será mostrada na Prévia da Missão"
   Target_uk_ua "Чи буде опис доступний на етапі попереднього перегляду"
   Modified 1642793857
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620BEE5A72E9}" {
   Id "PS-EditorAttribute_MissionDescription_Factions"
   Target_en_us "Show to factions"
   Target_fr_fr "Montrer aux factions"
   Target_es_es "Mostrar a bandos"
   Target_pl_pl "Pokaż frakcjom"
   Target_ru_ru "Показать фракциям"
   Target_pt_br "Mostrar para as facçoes"
   Target_uk_ua "Показати фракціям"
   Modified 1642793867
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620BF214E3D0}" {
   Id "PS-EditorAttribute_MissionDescription_Factions_Description"
   Target_en_us "This description will be shown to selected factions"
   Target_fr_fr "Cette description sera affichée aux factions sélectionnées"
   Target_es_es "Esta descripcion se mostrara a bandos selecionados"
   Target_pl_pl "Ten opis będzie pokazywany do wybranych frakcji"
   Target_ru_ru "Это описание будет доступно выбранным фракциям"
   Target_pt_br "Esta descrição será mostrada para facções selecionadas"
   Target_uk_ua "Цей опис буде доступний обраним фракціям"
   Modified 1642793888
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620BCDCE1FDF}" {
   Id "PS-EditorAttribute_MissionDescription_TextData"
   Target_en_us "Text data"
   Target_fr_fr "Données texte"
   Target_es_es "Datos de texto"
   Target_pl_pl "Tekst"
   Target_ru_ru "Текст"
   Target_pt_br "Dados de texto"
   Target_uk_ua "Текст"
   Modified 1642793894
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620BD39D1418}" {
   Id "PS-EditorAttribute_MissionDescription_TextData_Description"
   Target_en_us "Description tab text"
   Target_fr_fr "Texte de l'onglet Description"
   Target_es_es "Texto de la pestaña descripcion"
   Target_pl_pl "Tekst z strony opisowej"
   Target_ru_ru "Текст в вкладке описания"
   Target_pt_br "Texto da guia de descrição"
   Target_uk_ua "Текст у вкладці опису"
   Modified 1642793902
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620A25565F4F}" {
   Id "PS-EditorAttribute_MissionDescription_Title"
   Target_en_us "Title"
   Target_fr_fr "Titre"
   Target_es_es "Titulo"
   Target_pl_pl "Tytuł"
   Target_ru_ru "Заголовок"
   Target_pt_br "Titulo"
   Target_uk_ua "Заголовок"
   Modified 1642793908
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620A2941F17B}" {
   Id "PS-EditorAttribute_MissionDescription_Title_Description"
   Target_en_us "Tab title with mission description"
   Target_fr_fr "Titre de l'onglet avec description de la mission"
   Target_es_es "Pestaña del titulo con la descripcion de la mision"
   Target_pl_pl "Tytuł strony z opisem misji"
   Target_ru_ru "Заголовок вкладки с описанием миссии"
   Target_pt_br "Título da aba com descrição da missão"
   Target_uk_ua "Заголовок вкладки з описом місії"
   Modified 1642793914
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AF03B543FAF6A}" {
   Id "PS-EditorAttribute_Playable_IsPlayable"
   Target_en_us "Is playable"
   Target_fr_fr "Est jouable"
   Target_es_es "Es jugable"
   Target_pl_pl "Jest grywalny"
   Target_ru_ru "Играбельный"
   Target_pt_br "Jogavel"
   Target_uk_ua "Іграбельний"
   Modified 1642793924
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AF03B5602B638}" {
   Id "PS-EditorAttribute_Playable_IsPlayable_Description"
   Target_en_us "Players can play as this unit/squad"
   Target_fr_fr "Les joueurs peuvent jouer avec cette unité/équipe"
   Target_es_es "Jugadores pueden jugar como esta unidad/escuadra"
   Target_pl_pl "Gracze mogą grać jako ta jednostka/drużyna"
   Target_ru_ru "Игроки смогут играть за этого персонажа/группу"
   Target_pt_br "Os jogadores podem jogar como esta unidade/esquadrão"
   Target_uk_ua "Гравці зможуть грати за цього персонажа/групу"
   Modified 1642793931
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF9620A4444DA9C}" {
   Id "PS-EditorCategory_Lobby"
   Target_en_us "Reforger Lobby"
   Target_fr_fr "Reforger Lobby"
   Target_es_es "Reforger Lobby"
   Target_pl_pl "Reforger Lobby"
   Target_ru_ru "Рефоргер Лобби"
   Target_pt_br "Reforger Lobby"
   Target_uk_ua "Рефоргер лобі"
   Modified 1642793937
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EF962097FA8C778}" {
   Id "PS-EditorEntity_MissionDescription_Name"
   Target_en_us "Mission description"
   Target_fr_fr "Descriptif de la mission"
   Target_es_es "Descripcion de la mision"
   Target_pl_pl "Opis misji"
   Target_ru_ru "Описание миссии"
   Target_pt_br "Descriçao da Missao"
   Target_uk_ua "Опис місії"
   Modified 1642793948
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F2B43CA207C0B28}" {
   Id "PS-Freeze_End"
   Target_en_us "Freezetime is over!"
   Target_fr_fr "Le Freezetime est terminé!"
   Target_es_es "¡La fase de preparación ha terminado!"
   Target_pl_pl "Zamrożenie czasu"\
   "się zakończyło!"
   Target_ru_ru "Фризтайм окончен!"
   Target_pt_br "A fase de preparaçao Terminou"
   Target_uk_ua "Фризтайм закінчився!"
   Modified 1642793953
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{62BACE83CFDBF464}" {
   Id "PS-Freeze_time"
   Target_en_us "Preparing for battle"
   Target_ru_ru "Подготовка к бою"
   Modified 1656410513
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{64A31A3A9D99C14A}" {
   Id "PS-Freeze_time_advanced"
   Target_en_us "Freeze time advanced"
   Modified 1688419146
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{64A31A3AA5151141}" {
   Id "PS-Freeze_time_force_end"
   Target_en_us "Freeze time force ended"
   Modified 1688419161
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EB30CD4368261A7}" {
   Id "PS-GameMaster_PlayableGroup"
   Target_en_us "Playable Unit"
   Target_fr_fr "Unité jouable"
   Target_es_es "Unidad jugable"
   Target_pl_pl "Grywalna jednostka"
   Target_ru_ru "Играбельный чел"
   Target_pt_br "Unidade Jogavel"
   Target_uk_ua "Іграбельний чєл"
   Modified 1642793959
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE506E004252}" {
   Id "PS-GameModeHeader_Advance"
   Target_en_us "Advance"
   Target_fr_fr "Avance"
   Target_es_es "Avanzar"
   Target_pl_pl "Dalej"
   Target_ru_ru "Далее"
   Target_pt_br "Avançar"
   Target_uk_ua "Далі"
   Modified 1642793963
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{60D306C0DDCFA677}" {
   Id "PS-GameModeHeader_Author"
   Target_en_us "Author"
   Target_fr_fr "Auteur"
   Target_es_es "Autor"
   Target_pl_pl "Autor"
   Target_ru_ru "Автор"
   Target_pt_br "Autor"
   Target_uk_ua "Автор"
   Modified 1642793967
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE5226347A67}" {
   Id "PS-GameModeHeader_Briefing"
   Target_en_us "Briefing"
   Target_fr_fr "Briefing"
   Target_es_es "Briefing"
   Target_pl_pl "Sprawozdanie"
   Target_ru_ru "Брифинг"
   Target_pt_br "Briefing"
   Target_uk_ua "Брифінг"
   Modified 1642793971
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE52166ABC2A}" {
   Id "PS-GameModeHeader_Debriefing"
   Target_en_us "Debriefing"
   Target_fr_fr "Debriefing"
   Target_es_es "Debriefing"
   Target_pl_pl "Odprawa"
   Target_ru_ru "Итоги"
   Target_pt_br "Debriefing"
   Target_uk_ua "Підсумки"
   Modified 1642793975
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE523BA20242}" {
   Id "PS-GameModeHeader_InGame"
   Target_en_us "Game"
   Target_fr_fr "Jeu"
   Target_es_es "Juego"
   Target_pl_pl "Gra"
   Target_ru_ru "Игра"
   Target_pt_br "Jogo"
   Target_uk_ua "Гра"
   Modified 1642793979
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE5256808E8E}" {
   Id "PS-GameModeHeader_Lobby"
   Target_en_us "Lobby"
   Target_fr_fr "Lobby"
   Target_es_es "Lobby"
   Target_pl_pl "Lobby"
   Target_ru_ru "Лобби"
   Target_pt_br "Lobby"
   Target_uk_ua "Лобі"
   Modified 1642793988
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE52778D1F25}" {
   Id "PS-GameModeHeader_Preview"
   Target_en_us "Mission Preview"
   Target_fr_fr "Aperçu"
   Target_es_es "Previsualizado"
   Target_pl_pl "Podgląd misji"
   Target_ru_ru "Предпросмотр"
   Target_pt_br "Preview da Missao"
   Target_uk_ua "Передпрогляд"
   Modified 1642795123
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF40044FB3}" {
   Id "PS-Keybind_Comms_Playable_Selector"
   Target_en_us "Team switch"
   Target_fr_fr "Changement d'équipe"
   Target_es_es "Cambio de equipo"
   Target_pl_pl "Zmiana drużyn"
   Target_ru_ru "Смена роли"
   Target_pt_br "Troca de Equipe"
   Target_uk_ua "Зміна ролі"
   Modified 1642794006
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932C446D469ED}" {
   Id "PS-Keybind_CommsOpenLobby"
   Target_en_us "Open lobby"
   Target_fr_fr "Ouvrir le lobby"
   Target_es_es "Abrir Lobby"
   Target_pl_pl "Otwórz lobby"
   Target_ru_ru "Открыть лобби"
   Target_pt_br "Abrir Lobby"
   Target_uk_ua "Відкрити лобі"
   Modified 1642794180
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47EDD8EAD31}" {
   Id "PS-Keybind_MissionDescriptionSwitch"
   Target_en_us "Mission description interface"
   Target_fr_fr "Interface de description de mission"
   Target_es_es "Interfaz de descripcion de la mision"
   Target_pl_pl "Interfejs opisu misji"
   Target_ru_ru "Интерфейс описания миссии"
   Target_pt_br "Interface de descriçao da Missao"
   Target_uk_ua "Інтерфейс опису місії"
   Modified 1642794198
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC5311F4BC93B53}" {
   Id "PS-Keybind_SwitchSpectatorUI"
   Target_en_us "Hide/Show UI"
   Target_fr_fr "Masquer/Afficher l'UI"
   Target_es_es "Ocultar/Mostrar UI"
   Target_pl_pl "Schowaj/Pokaż UI"
   Target_ru_ru "Скрыть/Показать UI"
   Target_pt_br "Ocultar/Mostrar UI"
   Target_uk_ua "Сховати/Показати UI"
   Modified 1642794205
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47EA1E2244F}" {
   Id "PS-Keybind_VoiceChatSwitch"
   Target_en_us "Voice chat interface"
   Target_fr_fr "Interface de discussion vocale"
   Target_es_es "Interfaz del chat de voz"
   Target_pl_pl "Interfejs czatu głosowego"
   Target_ru_ru "Интерфейс голосового чата"
   Target_pt_br "Interface do Chat de voz"
   Target_uk_ua "Інтерфейс голосового чату"
   Modified 1642794209
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941A166E74B}" {
   Id "PS-Lobby_Chat"
   Target_en_us "Chat"
   Target_fr_fr "Chat"
   Target_es_es "Chat"
   Target_pl_pl "Czat"
   Target_ru_ru "Чат"
   Target_pt_br "Chat"
   Target_uk_ua "Чат"
   Modified 1642794214
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF442B2167}" {
   Id "PS-Lobby_Factions"
   Target_en_us "Factions"
   Target_fr_fr "Factions"
   Target_es_es "Bandos"
   Target_pl_pl "Frakcje"
   Target_ru_ru "Фракции"
   Target_pt_br "Facçoes"
   Target_uk_ua "Фракції"
   Modified 1642794219
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932EC5F220341}" {
   Id "PS-Lobby_ForceStart"
   Target_en_us "Start game"
   Target_fr_fr "Démarrer la partie"
   Target_es_es "Iniciar juego"
   Target_pl_pl "Zacznij gre"
   Target_ru_ru "Начать игру"
   Target_pt_br "Iniciar jogo"
   Target_uk_ua "Почати гру"
   Modified 1642794224
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F2AF2E6BD2B3ADB}" {
   Id "PS-Lobby_Inventory"
   Target_en_us "Open inventory"
   Target_fr_fr "Ouvrir l'inventaire"
   Target_es_es "Abrir el inventario"
   Target_pl_pl "Otwórz ekwipunek"
   Target_ru_ru "Открыть инвентарь"
   Target_pt_br "Abrir inventario"
   Target_uk_ua "Відкрити інвентар"
   Modified 1642794241
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932EA0659A8C5}" {
   Id "PS-Lobby_Join"
   Target_en_us "Join game"
   Target_fr_fr "Rejoindre la partie"
   Target_es_es "Unirse al juego"
   Target_pl_pl "Dołącz do gry"
   Target_ru_ru "Вступить в игру"
   Target_pt_br "Entrar no jogo"
   Target_uk_ua "Вступити в гру"
   Modified 1642794249
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932E9950F27EF}" {
   Id "PS-Lobby_JoinAsObserver"
   Target_en_us "Spectate"
   Target_fr_fr "Regarder la partie"
   Target_es_es "Espectador"
   Target_pl_pl "Oglądaj"
   Target_ru_ru "Наблюдать"
   Target_pt_br "Espectador"
   Target_uk_ua "Спостерегати"
   Modified 1642794268
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF46DC78AF}" {
   Id "PS-Lobby_LoadoutPreview"
   Target_en_us "Loadout Preview"
   Target_fr_fr "Aperçu du Loadout"
   Target_es_es "Equipamiento"
   Target_pl_pl "Podgląd ekwipunku"
   Target_ru_ru "Предпросмотр"
   Target_pt_br "Loadout Preview"
   Target_uk_ua "Екіпірування"
   Modified 1642794276
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EAEBB2F34252729}" {
   Id "PS-Lobby_OpenMenu"
   Target_en_us "Open menu"
   Target_fr_fr "Ouvrir le menu"
   Target_es_es "Abrir menu"
   Target_pl_pl "Otwórz menu"
   Target_ru_ru "Открыть меню"
   Target_pt_br "Abrir menu"
   Target_uk_ua "Відкрити меню"
   Modified 1642794281
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF798A6D5B}" {
   Id "PS-Lobby_Players"
   Target_en_us "Players"
   Target_fr_fr "Joueurs"
   Target_es_es "Jugadores"
   Target_pl_pl "Gracze"
   Target_ru_ru "Игроки"
   Target_pt_br "Jogadores"
   Target_uk_ua "Гравці"
   Modified 1642794285
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB753E7EBC5365D}" {
   Id "PS-Lobby_PlayersList"
   Target_en_us "List"
   Target_fr_fr "Liste"
   Target_es_es "Lista"
   Target_pl_pl "Lista"
   Target_ru_ru "Список"
   Target_pt_br "Lista"
   Target_uk_ua "Список"
   Modified 1642794289
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941AE8846DA}" {
   Id "PS-Lobby_Ready"
   Target_en_us "Ready"
   Target_fr_fr "Prêt"
   Target_es_es "Preparado"
   Target_pl_pl "Gotów"
   Target_ru_ru "Готов"
   Target_pt_br "Preparado"
   Target_uk_ua "Готовий"
   Modified 1642794297
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F2B43CA55192971}" {
   Id "PS-Lobby_RoleKick"
   Target_en_us "You were kicked from role!"
   Target_fr_fr "Vous avez été expulsé de votre rôle!"
   Target_es_es "¡Te expulsaron del puesto!"
   Target_pl_pl "Zostałeś wyrzucony z roli!"
   Target_ru_ru "Вас выгнали с роли!"
   Target_pt_br "Te expulsaram da função"
   Target_uk_ua "Вас вигнали з ролі!"
   Modified 1642794310
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF7D6EDF21}" {
   Id "PS-Lobby_Roles"
   Target_en_us "Roles"
   Target_fr_fr "Rôles"
   Target_es_es "Roles"
   Target_pl_pl "Role"
   Target_ru_ru "Роли"
   Target_pt_br "Funçoes"
   Target_uk_ua "Ролі"
   Modified 1642794320
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47913C55F2C}" {
   Id "PS-Lobby_VoiceChat"
   Target_en_us "Voice Chat"
   Target_fr_fr "Chat vocal"
   Target_es_es "Chat de voz"
   Target_pl_pl "Czat głosowy"
   Target_ru_ru "Голосовой чат"
   Target_pt_br "Chat de voz"
   Target_uk_ua "Голосовий чат"
   Modified 1642794325
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC2E47910530FBD}" {
   Id "PS-Lobby_VoiceChatFaction"
   Target_en_us "Faction voice chat"
   Target_fr_fr "Chat vocal de faction"
   Target_es_es "Chat de voz de bando"
   Target_pl_pl "Czat głosowy frakcji"
   Target_ru_ru "Фракционный голосовой чат"
   Target_pt_br "Chat de voz da facçao"
   Target_uk_ua "Голосовий чат фракції"
   Modified 1642794330
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0AFCF3DCDE6333}" {
   Id "PS-MissionDescription_Header"
   Target_en_us "Mission description"
   Target_fr_fr "Descriptif de la mission"
   Target_es_es "Descripcion de mision"
   Target_pl_pl "Opis misji"
   Target_ru_ru "Описание миссии"
   Target_pt_br "Descrição da missao"
   Target_uk_ua "Опис місії"
   Modified 1642794337
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{60BA84375EEF27A8}" {
   Id "PS-ObjectiveLevel_Draw"
   Target_en_us "Draw"
   Target_fr_fr "Match nul"
   Target_es_es "Dibujar"
   Target_pl_pl "Remis"
   Target_ru_ru "Ничья"
   Target_pt_br "Empate"
   Target_uk_ua "Нічия"
   Modified 1642794341
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{60BA84378C867415}" {
   Id "PS-ObjectiveLevel_MajorLoss"
   Target_en_us "Major defeat"
   Target_fr_fr "Défaite majeure"
   Target_es_es "Gran derrota"
   Target_pl_pl "Znaczna przegrana"
   Target_ru_ru "Поражение"
   Target_pt_br "Grande derrota"
   Target_uk_ua "Поразка"
   Modified 1642794350
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{60BA843705762142}" {
   Id "PS-ObjectiveLevel_MajorVictory"
   Target_en_us "Major victory"
   Target_fr_fr "Victoire majeure"
   Target_es_es "Gran victoria"
   Target_pl_pl "Znaczne zwycięstwo"
   Target_ru_ru "Победа"
   Target_pt_br "Grande vitória"
   Target_uk_ua "Перемога"
   Modified 1642794355
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{60BA8437AF9DA0F3}" {
   Id "PS-ObjectiveLevel_MinorLoss"
   Target_en_us "Minor defeat"
   Target_fr_fr "Défaite mineure"
   Target_es_es "Derrota menor"
   Target_pl_pl "Niewielka przegrana"
   Target_ru_ru "Незначительное поражение"
   Target_pt_br "Derrota menor"
   Target_uk_ua "Мала поразка"
   Modified 1642794363
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{60BA84377297495A}" {
   Id "PS-ObjectiveLevel_MinorVictory"
   Target_en_us "Minor victory"
   Target_fr_fr "Victoire mineure"
   Target_es_es "Victoria menor"
   Target_pl_pl "Niewielkie zwycięstwo"
   Target_ru_ru "Незначительная победа"
   Target_pt_br "Vitória menor"
   Target_uk_ua "Мала перемога"
   Modified 1642794371
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EBE323E513FFB52}" {
   Id "PS-ObserverPlayersList"
   Target_en_us "Alive players"
   Target_fr_fr "Joueurs vivants"
   Target_es_es "Jugadores vivos"
   Target_pl_pl "Żyjący gracze"
   Target_ru_ru "Живые игроки"
   Target_pt_br "Jogadores vivos"
   Target_uk_ua "Живі гравці"
   Modified 1642794375
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EBE323E40F74A24}" {
   Id "PS-Preview_PleaseWait"
   Target_en_us "Please wait"\
   "Game will start soon"
   Target_fr_fr "S'il vous plaît, attendez"\
   "La partie va bientôt commencer"
   Target_es_es "Por favor espera"\
   "La partida comenzara pronto"
   Target_pl_pl "Proszę poczekać"\
   "Gra zacznie się w krótce"
   Target_ru_ru "Пожалуйста подождите"\
   "Игра скоро начнётся"
   Target_pt_br "Por favor espere"\
   "A partida começara logo"
   Target_uk_ua "Будь ласка зачекайте"\
   "Гра скоро почнеться"
   Modified 1642794412
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EC5311F409ED937}" {
   Id "PS-Spectator_SwitchSpectatorUI"
   Target_en_us "Hide/Show UI"
   Target_fr_fr "Masquer/Afficher l'UI"
   Target_es_es "Ocultar/Mostrar UI"
   Target_pl_pl "Schowaj/Pokaż UI"
   Target_ru_ru "Скрыть/Показать UI"
   Target_pt_br "Ocultar/Mostrar UI"
   Target_uk_ua "Сховати/Показати UI"
   Modified 1642794418
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6E12BC67891C4}" {
   Id "PS-VoNRoom_Command"
   Target_en_us "HQ"
   Target_fr_fr "HQ"
   Target_es_es "Mando"
   Target_pl_pl "Sztab"
   Target_ru_ru "Штаб"
   Target_pt_br "Comando"
   Target_uk_ua "Штаб"
   Modified 1642794425
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6E12BC05F7F27}" {
   Id "PS-VoNRoom_Faction"
   Target_en_us "Faction"
   Target_fr_fr "Faction"
   Target_es_es "Bando"
   Target_pl_pl "Frakcja"
   Target_ru_ru "Фракция"
   Target_pt_br "Facção"
   Target_uk_ua "Фракція"
   Modified 1642794435
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6E12BF9F8C213}" {
   Id "PS-VoNRoom_Global"
   Target_en_us "Global"
   Target_fr_fr "Global"
   Target_es_es "Global"
   Target_pl_pl "Globalny"
   Target_ru_ru "Глобальный"
   Target_pt_br "Global"
   Target_uk_ua "Глобальний"
   Modified 1642794440
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE5384337A16}" {
   Id "PS-VoNRoom_Header"
   Target_en_us "Voice сhannels"
   Target_fr_fr "Canaux vocaux"
   Target_es_es "Canales de voz"
   Target_pl_pl "Kanały głosowe"
   Target_ru_ru "Голосовые каналы"
   Target_pt_br "Canal de voz"
   Target_uk_ua "Голосові канали"
   Modified 1642794445
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0C9CB1CF9CE91D}" {
   Id "PS-VoNRoom_Local"
   Target_en_us "Deafen"
   Target_fr_fr "Assourdir"
   Target_es_es "Silenciar"
   Target_pl_pl "Wycisz"
   Target_ru_ru "Откл.звук"
   Target_pt_br "Silenciar"
   Target_uk_ua "Вимк.звук"
   Modified 1642794457
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5F0C9CB1EFDDDB2E}" {
   Id "PS-VoNRoom_Public"
   Target_en_us "public channel"
   Target_fr_fr "canal public"
   Target_es_es "canal publico"
   Target_pl_pl "kanał publiczny"
   Target_ru_ru "публичный канал"
   Target_pt_br "canal publico"
   Target_uk_ua "публичний канал"
   Modified 1642794511
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{6461467B3A1EE049}" {
   Id "PS_Lobby_DefaultSquadCustom"
   Target_en_us "Squad"
   Target_ru_ru "Отряд"
   Modified 1684208584
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{6461467CBF9676FA}" {
   Id "PS_Lobby_Locked"
   Target_en_us "Locked"
   Target_ru_ru "Закрыт"
   Modified 1684210906
   Author "zazul"
   LastChanged "zazul"
  }
 }
}