StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5EC5311E4F6DC81D}" {
   Id "PS-Briefing_GroupVoiceChat"
   Target_en_us "Group сhat"
   Target_es_es "Chat de Grupo"
   Target_ru_ru "Отрядный чат"
   Target_pt_br "Group сhat"
   Target_uk_ua "Чат загону"
   Modified 1625890283
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC2E46366D61D92}" {
   Id "PS-Briefing_MissionDescriptionHeader"
   Target_en_us "Mission description"
   Target_es_es "Descripcion de mision"
   Target_ru_ru "Описание сценария"
   Target_pt_br "Descrição da Missão"
   Target_uk_ua "Опис сценарію"
   Modified 1625890274
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC2E47F1F2FA6D1}" {
   Id "PS-Briefing_MissionDescriptionHide"
   Target_en_us "Hide mission description"
   Target_es_es "Ocultar descripcion de mision"
   Target_ru_ru "Скрыть описание миссии"
   Target_pt_br "Ocultar descrição da missão"
   Target_uk_ua "Сховати опис місії"
   Modified 1625890268
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC2E47F0691875D}" {
   Id "PS-Briefing_MissionDescriptionShow"
   Target_en_us "Show mission description"
   Target_es_es "Mostrar descripcion de mision"
   Target_ru_ru "Показать описание миссии"
   Target_pt_br "Mostrar descrição da missão"
   Target_uk_ua "Показати опис місії"
   Modified 1625890260
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0AFCF3D60D9339}" {
   Id "PS-Briefing_PlayableNotSelected"
   Target_en_us "Role are not selected!"\
   "On mission start you will become a spectator!"
   Target_es_es "No has seleccionado rol!"\
   "Comenzaras la mision como espectador!"
   Target_ru_ru "Роль не выбрана!"\
   "На старте миссии вы станете наблюдателем!"
   Target_pt_br "A função não está selecionada!"\
   "No início da missão você se tornará um espectador!"
   Target_uk_ua "Роль не обрано!"\
   "На старті місії ви станете спостерігачем!"
   Modified 1625890251
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0AFCF3B4D7E97D}" {
   Id "PS-Briefing_Steps"
   Target_en_us "Steps"
   Target_es_es "Pasos a seguir"
   Target_pt_br "Etapas do briefing"
   Target_uk_ua "Етапи"
   Modified 1625890208
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC5311E7A654D14}" {
   Id "PS-Briefing_VoiceChat"
   Target_en_us "Voice chat"
   Target_es_es "Chat de voz"
   Target_ru_ru "Голосовой чат"
   Target_pt_br "Chat de voz"
   Target_uk_ua " Голосовий чат"
   Modified 1625890185
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC2E47F1C0F3895}" {
   Id "PS-Briefing_VoiceChatHide"
   Target_en_us "Hide voice chat"
   Target_es_es "Ocultar chat de voz"
   Target_ru_ru "Скрыть голосовой чат"
   Target_pt_br "Ocultar chat de voz"
   Target_uk_ua "Сховати голосовий чат"
   Modified 1625890177
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC2E47F00BC0D4E}" {
   Id "PS-Briefing_VoiceChatShow"
   Target_en_us "Show voice chat"
   Target_es_es "Mostrar chat de voz"
   Target_ru_ru "Показать голосовой чат"
   Target_pt_br "Mostrar chat de voz"
   Target_uk_ua "Показати голосовий чат"
   Modified 1625890164
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0F44E18237239B}" {
   Id "PS-Briefing_YourPlace"
   Target_en_us "Start position"
   Target_es_es "Posición de salida"
   Target_ru_ru "Стартовая позиция"
   Target_pt_br "Posição de Inicio"
   Target_uk_ua "Стартова позиція"
   Modified 1625890158
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC2E474747EACEA}" {
   Id "PS-Debrief_Losses"
   Target_en_us "Faction statistic"
   Target_es_es "Estadisticas de bando"
   Target_ru_ru "Статистика фракции"
   Target_pt_br "Estatística da facção"
   Target_uk_ua "Статистика фракції"
   Modified 1625890152
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC2E4747D62E00C}" {
   Id "PS-Debrief_Objectives"
   Target_en_us "Objectives"
   Target_es_es "Objectivos"
   Target_ru_ru "Задачи"
   Target_pt_br "Objetivos"
   Target_uk_ua "Завдання"
   Modified 1625890145
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC27C54DBE99E97}" {
   Id "PS-Description_HeaderAboutMission"
   Target_en_us "General information"
   Target_es_es "Informacion general"
   Target_ru_ru "Общая информация"
   Target_pt_br "Informaçoes Gerais"
   Target_uk_ua "Загальна інформація"
   Modified 1625890134
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC27C54EAA8176D}" {
   Id "PS-Description_HeaderFIA"
   Target_en_us "FIA objectives"
   Target_es_es "Objetivos FIA"
   Target_ru_ru "Задачи FIA"
   Target_pt_br "Objetivos FIA"
   Target_uk_ua "Завдання FIA"
   Modified 1625890125
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC27C54DD5C222E}" {
   Id "PS-Description_HeaderObjectives"
   Target_en_us "Objectives"
   Target_es_es "Objectivos"
   Target_ru_ru "Задачи"
   Target_pt_br "Objetivos"
   Target_uk_ua "Завдання"
   Modified 1625890050
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC27C54E131620A}" {
   Id "PS-Description_HeaderRules"
   Target_en_us "Rules"
   Target_es_es "Reglas"
   Target_ru_ru "Правила"
   Target_pt_br "Regras"
   Target_uk_ua "Правила"
   Modified 1625890040
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC27C54ED9CAFBA}" {
   Id "PS-Description_HeaderUS"
   Target_en_us "US Army objectives"
   Target_es_es "Objetivos US Army"
   Target_ru_ru "Задачи Армии США"
   Target_pt_br "Objetivo Exercito americano"
   Target_uk_ua "Завдання Армії США"
   Modified 1625890034
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC27C54F35F3D06}" {
   Id "PS-Description_HeaderUSSR"
   Target_en_us "Soviet Army objectives"
   Target_es_es "Objetivos Sovieticos"
   Target_ru_ru "Задачи Советской Армии"
   Target_pt_br "Objetivo Exercito Soviético"
   Target_uk_ua "Завдання Радянської Армії"
   Modified 1625890028
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF96208D034F2DA}" {
   Id "PS-EditorAttribute_GameModeCoop_CanOpenLobbyInLobby"
   Target_en_us "Team Switch"
   Target_es_es "Cambio de bando"
   Target_ru_ru "Смена роли"
   Target_pt_br "Troca de Times"
   Target_uk_ua "Зміна ролі"
   Modified 1625890021
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF96208D5FE09A6}" {
   Id "PS-EditorAttribute_GameModeCoop_CanOpenLobbyInLobby_Description"
   Target_en_us "Any player will be able to access the lobby during a mission and change role"
   Target_es_es "Cualquier jugador tiene acceso al lobby durante la partida"
   Target_ru_ru "Любой игрок сможет получить доступ в лобби во время миссии и сменить роль"
   Target_pt_br "Qualquer jogador poderá acessar o lobby durante uma missão e mudar de função"
   Target_uk_ua "Будь-який гравець зможе отримати доступ до лобі під час місії та змінити роль"
   Modified 1625889991
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0AED380F307AC1}" {
   Id "PS-EditorAttribute_GameModeCoop_DisableLeaderSquadMarkers"
   Target_en_us "Disable squad leader markers"
   Target_es_es "Deshabilita marcas de lideres de escuadras"
   Target_ru_ru "Отключить маркера лидеров отрядов"
   Target_pt_br "Desativar marcadores de líder de esquadrão"
   Target_uk_ua "Вимкнути маркери лідерів загонів"
   Modified 1625889976
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0AED38124D830C}" {
   Id "PS-EditorAttribute_GameModeCoop_DisableLeaderSquadMarkers_Description"
   Target_en_us "Squad leaders markers will not appear on the map."
   Target_es_es "Las marcas de lideres de escuadra no apareceran en el mapa"
   Target_ru_ru "Маркеры лидеров отрядов не будут отображены на карте"
   Target_pt_br "Marcaçoes de lideres de Esquadrao não irao aparecer no mapa"
   Target_uk_ua "Маркери лідерів загонів не будуть відображені на карті"
   Modified 1625890116
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620B44BDD42D}" {
   Id "PS-EditorAttribute_GameModeCoop_FreezeTime"
   Target_en_us "Freeze time"
   Target_es_es "Momentos congelados"
   Target_ru_ru "Фризтайм"
   Target_pt_br "Tempo de congelamento"
   Target_uk_ua "Фризтайм"
   Modified 1625889911
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620B4932D858}" {
   Id "PS-EditorAttribute_GameModeCoop_FreezeTime_Description"
   Target_en_us "Time from mission start to removal of containment zones"
   Target_es_es "Tiempo para quitar las zonas de retencion"
   Target_ru_ru "Время со старта миссии до удаления зон ограничения"
   Target_pt_br "Tempo desde o início da missão até a remoção das zonas de contenção"
   Target_uk_ua "Час зі старту місії до видалення зон обмеження"
   Modified 1625889905
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620B03413635}" {
   Id "PS-EditorAttribute_GameModeCoop_ReconnectTime"
   Target_en_us "Reconnect time"
   Target_es_es "Tiempo de reconexion"
   Target_ru_ru "Время для переподключения"
   Target_pt_br "Tempo de reconexão"
   Target_uk_ua "Час для перепідключення"
   Modified 1625889891
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620B07CEB34C}" {
   Id "PS-EditorAttribute_GameModeCoop_ReconnectTime_Description"
   Target_en_us "Player role reservation time for reconnection"
   Target_es_es "Reserva de tiempo para la reconexion del jugador"
   Target_ru_ru "Время резервации роли игрока для переподключения"
   Target_pt_br "Tempo de reserva da função do jogador para reconexão"
   Target_uk_ua "Час резервації ролі гравця для перепідключення"
   Modified 1625889884
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620B1D5BEAA7}" {
   Id "PS-EditorAttribute_GameModeCoop_RemoveRedundantUnits"
   Target_en_us "Remove redundant units"
   Target_es_es "Borrar unidades redundantes"
   Target_ru_ru "Удалить незанятых персонажей"
   Target_pt_br "Remova unidades redundantes"
   Target_uk_ua "Видалити незайнятих персонажів"
   Modified 1625889875
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620B20207DC0}" {
   Id "PS-EditorAttribute_GameModeCoop_RemoveRedundantUnits_Description"
   Target_en_us "Delete not used playable units on mission start"
   Target_es_es "Borra las unidades jugables sin jugador al comienzo de la partida"
   Target_ru_ru "Удалить незанятых персонажей на старте миссии"
   Target_pt_br "Exclua unidades jogáveis não utilizadas no início da missão"
   Target_uk_ua "Видалити незайнятих персонажів на старті місії"
   Modified 1625889868
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0AED380A4931C1}" {
   Id "PS-EditorAttribute_GameModeCoop_ShowMarkersOnlyOnBriefing"
   Target_en_us "Map markers can be placed only on briefing by squad leaders"
   Target_es_es "Los marcadores en el mapa solo pueden colocarlos los lideres de escuadra"
   Target_ru_ru "Маркеры на карте могут быть поставлены только на брифинге лидерами отрядов"
   Target_pt_br "Marcaçoes de mapa só podem ser colocados durante instruções dos líderes de esquadrão"
   Target_uk_ua "Маркери на карті можуть бути поставлені тільки на брифінгу лідерами загонів"
   Modified 1625889859
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0AED380D9701A9}" {
   Id "PS-EditorAttribute_GameModeCoop_ShowMarkersOnlyOnBriefing_Description"
   Target_en_us "Prevents players from placing markers after the briefing and also if they are not the leader of the squad"
   Target_es_es "Evita que los jugadores coloquen marcas despues del briefing si no son lideres de escuadra"
   Target_ru_ru "Запрещает игрокам ставить маркера после брифинга а также если они не лидеры отряда"
   Target_pt_br "Impede que os jogadores coloquem marcadores após o briefing e também se não forem o líder do Squad"
   Target_uk_ua "Забороняє гравцям ставити маркера після брифінгу а також якщо вони не лідери загону"
   Modified 1625889846
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620B995D2494}" {
   Id "PS-EditorAttribute_MissionDescription_FactionEmpty"
   Target_en_us "Show to empty faction"
   Target_es_es "Mostrar bando vacio"
   Target_ru_ru "Показать пустой фракции"
   Target_pt_br "Mostrar para facção vazia"
   Target_uk_ua "Показати порожній фракції"
   Modified 1625889833
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620B9D907696}" {
   Id "PS-EditorAttribute_MissionDescription_FactionEmpty_Description"
   Target_en_us "Will be this description shown on Mission Preview"
   Target_es_es "Se mostrara esta descripcion en la vista previa de la misión"
   Target_ru_ru "Будет ли описание доступно на этапе предпросмотра"
   Target_pt_br "Esta descrição será mostrada na Prévia da Missão"
   Target_uk_ua "Чи буде опис доступний на етапі попереднього перегляду"
   Modified 1625889809
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620BEE5A72E9}" {
   Id "PS-EditorAttribute_MissionDescription_Factions"
   Target_en_us "Show to factions"
   Target_es_es "Mostrar a bandos"
   Target_ru_ru "Показать фракциям"
   Target_pt_br "Mostrar para as facçoes"
   Target_uk_ua "Показати фракціям"
   Modified 1625889792
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620BF214E3D0}" {
   Id "PS-EditorAttribute_MissionDescription_Factions_Description"
   Target_en_us "This description will be shown to selected factions"
   Target_es_es "Esta descripcion se mostrara a bandos selecionados"
   Target_ru_ru "Это описание будет доступно выбранным фракциям"
   Target_pt_br "Esta descrição será mostrada para facções selecionadas"
   Target_uk_ua "Цей опис буде доступний обраним фракціям"
   Modified 1625889778
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620BCDCE1FDF}" {
   Id "PS-EditorAttribute_MissionDescription_TextData"
   Target_en_us "Text data"
   Target_es_es "Datos de texto"
   Target_ru_ru "Текст"
   Target_pt_br "Dados de texto"
   Target_uk_ua "Текст"
   Modified 1625889766
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620BD39D1418}" {
   Id "PS-EditorAttribute_MissionDescription_TextData_Description"
   Target_en_us "Description tab text"
   Target_es_es "Texto de la pestaña descripcion"
   Target_ru_ru "Текст в вкладке описания"
   Target_pt_br "Texto da guia de descrição"
   Target_uk_ua "Текст у вкладці опису"
   Modified 1625889759
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620A25565F4F}" {
   Id "PS-EditorAttribute_MissionDescription_Title"
   Target_en_us "Title"
   Target_es_es "Titulo"
   Target_ru_ru "Заголовок"
   Target_pt_br "Titulo"
   Target_uk_ua "Заголовок"
   Modified 1625889745
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620A2941F17B}" {
   Id "PS-EditorAttribute_MissionDescription_Title_Description"
   Target_en_us "Tab title with mission description"
   Target_es_es "Pestaña del titulo con la descripcion de la mision"
   Target_ru_ru "Заголовок вкладки с описанием миссии"
   Target_pt_br "Título da aba com descrição da missão"
   Target_uk_ua "Заголовок вкладки з описом місії"
   Modified 1625889739
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0AF03B543FAF6A}" {
   Id "PS-EditorAttribute_Playable_IsPlayable"
   Target_en_us "Is playable"
   Target_es_es "Es jugable"
   Target_ru_ru "Играбельный"
   Target_pt_br "Jogavel"
   Target_uk_ua "Іграбельний"
   Modified 1625889731
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0AF03B5602B638}" {
   Id "PS-EditorAttribute_Playable_IsPlayable_Description"
   Target_en_us "Players can play as this unit/squad"
   Target_es_es "Jugadores pueden jugar como esta unidad/escuadra"
   Target_ru_ru "Игроки смогут играть за этого персонажа/группу"
   Target_pt_br "Os jogadores podem jogar como esta unidade/esquadrão"
   Target_uk_ua "Гравці зможуть грати за цього персонажа/групу"
   Modified 1625889675
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF9620A4444DA9C}" {
   Id "PS-EditorCategory_Lobby"
   Target_en_us "Reforger Lobby"
   Target_es_es "Reforger Lobby"
   Target_ru_ru "Рефоргер Лобби"
   Target_pt_br "Reforger Lobby"
   Target_uk_ua "Рефоргер лобі"
   Modified 1625889652
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EF962097FA8C778}" {
   Id "PS-EditorEntity_MissionDescription_Name"
   Target_en_us "Mission description"
   Target_es_es "Descripcion de la mision"
   Target_ru_ru "Описание миссии"
   Target_pt_br "Descriçao da Missao"
   Target_uk_ua "Опис місії"
   Modified 1625889620
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5F2B43CA207C0B28}" {
   Id "PS-Freeze_End"
   Target_en_us "Freezetime is over!"
   Target_es_es "¡La fase de preparación ha terminado!"
   Target_ru_ru "Фризтайм окончен!"
   Target_pt_br "A fase de preparaçao Terminou"
   Target_uk_ua "Фризтайм закінчився!"
   Modified 1625889603
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EB30CD4368261A7}" {
   Id "PS-GameMaster_PlayableGroup"
   Target_en_us "Playable Unit"
   Target_es_es "Unidad jugable"
   Target_ru_ru "Играбельный чел"
   Target_pt_br "Unidade Jogavel"
   Target_uk_ua "Іграбельний чєл"
   Modified 1625889567
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EB6FE506E004252}" {
   Id "PS-GameModeHeader_Advance"
   Target_en_us "Advance"
   Target_es_es "Avanzar"
   Target_ru_ru "Далее"
   Target_pt_br "Avançar"
   Target_uk_ua "Далі"
   Modified 1625889538
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{60D306C0DDCFA677}" {
   Id "PS-GameModeHeader_Author"
   Target_en_us "Author"
   Target_es_es "Autor"
   Target_ru_ru "Автор"
   Target_pt_br "Autor"
   Target_uk_ua "Автор"
   Modified 1625890950
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE5226347A67}" {
   Id "PS-GameModeHeader_Briefing"
   Target_en_us "Briefing"
   Target_es_es "Briefing"
   Target_ru_ru "Брифинг"
   Target_pt_br "Briefing"
   Target_uk_ua "Брифінг"
   Modified 1625889513
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EB6FE52166ABC2A}" {
   Id "PS-GameModeHeader_Debriefing"
   Target_en_us "Debriefing"
   Target_es_es "Debriefing"
   Target_ru_ru "Итоги"
   Target_pt_br "Debriefing"
   Target_uk_ua "Підсумки"
   Modified 1625889502
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EB6FE523BA20242}" {
   Id "PS-GameModeHeader_InGame"
   Target_en_us "Game"
   Target_es_es "Juego"
   Target_ru_ru "Игра"
   Target_pt_br "Jogo"
   Target_uk_ua "Гра"
   Modified 1625889494
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EB6FE5256808E8E}" {
   Id "PS-GameModeHeader_Lobby"
   Target_en_us "Lobby"
   Target_es_es "Lobby"
   Target_ru_ru "Лобби"
   Target_pt_br "Lobby"
   Target_uk_ua "Лобі"
   Modified 1625889491
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EB6FE52778D1F25}" {
   Id "PS-GameModeHeader_Preview"
   Target_en_us "Mission Preview"
   Target_es_es "Previsualizado"
   Target_ru_ru "Предпросмотр"
   Target_pt_br "Preview da Missao"
   Target_uk_ua "Попередній перегляд місії"
   Modified 1625889486
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EA73DBF40044FB3}" {
   Id "PS-Keybind_Comms_Playable_Selector"
   Target_en_us "Team switch"
   Target_es_es "Cambio de equipo"
   Target_ru_ru "Смена роли"
   Target_pt_br "Troca de Equipe"
   Target_uk_ua "Зміна ролі"
   Modified 1625889400
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EA932C446D469ED}" {
   Id "PS-Keybind_CommsOpenLobby"
   Target_en_us "Open lobby"
   Target_es_es "Abrir Lobby"
   Target_ru_ru "Открыть лобби"
   Target_pt_br "Abrir Lobby"
   Target_uk_ua "Відкрити лобі"
   Modified 1625889453
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC2E47EDD8EAD31}" {
   Id "PS-Keybind_MissionDescriptionSwitch"
   Target_en_us "Mission description interface"
   Target_es_es "Interfaz de descripcion de la mision"
   Target_ru_ru "Интерфейс описания миссии"
   Target_pt_br "Interface de descriçao da Missao"
   Target_uk_ua "Інтерфейс опису місії"
   Modified 1625889380
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC5311F4BC93B53}" {
   Id "PS-Keybind_SwitchSpectatorUI"
   Target_en_us "Hide/Show UI"
   Target_es_es "Ocultar/Mostrar UI"
   Target_ru_ru "Скрыть/Показать UI"
   Target_pt_br "Ocultar/Mostrar UI"
   Target_uk_ua "Сховати/Показати UI"
   Modified 1625889336
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC2E47EA1E2244F}" {
   Id "PS-Keybind_VoiceChatSwitch"
   Target_en_us "Voice chat interface"
   Target_es_es "Interfaz del chat de voz"
   Target_ru_ru "Интерфейс голосового чата"
   Target_pt_br "Interface do Chat de voz"
   Target_uk_ua "Інтерфейс голосового чату"
   Modified 1625889308
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EA75941A166E74B}" {
   Id "PS-Lobby_Chat"
   Target_en_us "Chat"
   Target_es_es "Chat"
   Target_ru_ru "Чат"
   Target_pt_br "Chat"
   Target_uk_ua "Чат"
   Modified 1625891051
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF442B2167}" {
   Id "PS-Lobby_Factions"
   Target_en_us "Factions"
   Target_es_es "Bandos"
   Target_ru_ru "Фракции"
   Target_pt_br "Facçoes"
   Target_uk_ua "Фракції"
   Modified 1625889290
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EA932EC5F220341}" {
   Id "PS-Lobby_ForceStart"
   Target_en_us "Start game"
   Target_es_es "Iniciar juego"
   Target_ru_ru "Начать игру"
   Target_pt_br "Iniciar jogo"
   Target_uk_ua "Почати гру"
   Modified 1625889268
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5F2AF2E6BD2B3ADB}" {
   Id "PS-Lobby_Inventory"
   Target_en_us "Open inventory"
   Target_es_es "Abrir el inventario"
   Target_ru_ru "Открыть инвентарь"
   Target_pt_br "Abrir inventario"
   Target_uk_ua "Відкрити інвентар"
   Modified 1625889260
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EA932EA0659A8C5}" {
   Id "PS-Lobby_Join"
   Target_en_us "Join game"
   Target_es_es "Unirse al juego"
   Target_ru_ru "Вступить в игру"
   Target_pt_br "Entrar no jogo"
   Target_uk_ua "Вступити в гру"
   Modified 1625889246
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EA932E9950F27EF}" {
   Id "PS-Lobby_JoinAsObserver"
   Target_en_us "Spectate"
   Target_es_es "Espectador"
   Target_ru_ru "Наблюдать"
   Target_pt_br "Espectador"
   Target_uk_ua "Спостерегати"
   Modified 1625889210
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EA73DBF46DC78AF}" {
   Id "PS-Lobby_LoadoutPreview"
   Target_en_us "Loadout Preview"
   Target_es_es "Equipamiento"
   Target_ru_ru "Предпросмотр"
   Target_pt_br "Loadout Preview"
   Target_uk_ua "Екіпірування"
   Modified 1625889203
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EAEBB2F34252729}" {
   Id "PS-Lobby_OpenMenu"
   Target_en_us "Open menu"
   Target_es_es "Abrir menu"
   Target_ru_ru "Открыть меню"
   Target_pt_br "Abrir menu"
   Target_uk_ua "Відкрити меню"
   Modified 1625889126
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EA73DBF798A6D5B}" {
   Id "PS-Lobby_Players"
   Target_en_us "Players"
   Target_es_es "Jugadores"
   Target_ru_ru "Игроки"
   Target_pt_br "Jogadores"
   Target_uk_ua "Гравці"
   Modified 1625889110
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EB753E7EBC5365D}" {
   Id "PS-Lobby_PlayersList"
   Target_en_us "List"
   Target_es_es "Lista"
   Target_ru_ru "Список"
   Target_pt_br "Lista"
   Target_uk_ua "Список"
   Modified 1625889103
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EA75941AE8846DA}" {
   Id "PS-Lobby_Ready"
   Target_en_us "Ready"
   Target_es_es "Preparado"
   Target_ru_ru "Готов"
   Target_pt_br "Preparado"
   Target_uk_ua "Готовий"
   Modified 1625889088
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5F2B43CA55192971}" {
   Id "PS-Lobby_RoleKick"
   Target_en_us "You were kicked from role!"
   Target_es_es "¡Te expulsaron del puesto!"
   Target_ru_ru "Вас выгнали с роли!"
   Target_pt_br "Te expulsaram da função"
   Target_uk_ua "Вас вигнали з ролі!"
   Modified 1625889030
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EA73DBF7D6EDF21}" {
   Id "PS-Lobby_Roles"
   Target_en_us "Roles"
   Target_es_es "Roles"
   Target_ru_ru "Роли"
   Target_pt_br "Funçoes"
   Target_uk_ua "Ролі"
   Modified 1625888997
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC2E47913C55F2C}" {
   Id "PS-Lobby_VoiceChat"
   Target_en_us "Voice Chat"
   Target_es_es "Chat de voz"
   Target_ru_ru "Голосовой чат"
   Target_pt_br "Chat de voz"
   Target_uk_ua "Голосовий чат"
   Modified 1625888978
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC2E47910530FBD}" {
   Id "PS-Lobby_VoiceChatFaction"
   Target_en_us "Faction voice chat"
   Target_es_es "Chat de voz de bando"
   Target_ru_ru "Фракционный голосовой чат"
   Target_pt_br "Chat de voz da facçao"
   Target_uk_ua "Голосовий чат фракції"
   Modified 1625888946
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0AFCF3DCDE6333}" {
   Id "PS-MissionDescription_Header"
   Target_en_us "Mission description"
   Target_es_es "Descripcion de mision"
   Target_ru_ru "Описание миссии"
   Target_pt_br "Descrição da missao"
   Target_uk_ua "Опис місії"
   Modified 1625888968
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{60BA84375EEF27A8}" {
   Id "PS-ObjectiveLevel_Draw"
   Target_en_us "Draw"
   Target_es_es "Dibujar"
   Target_ru_ru "Ничья"
   Target_pt_br "Empate"
   Target_uk_ua "Нічия"
   Modified 1625890886
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{60BA84378C867415}" {
   Id "PS-ObjectiveLevel_MajorLoss"
   Target_en_us "Major defeat"
   Target_es_es "Gran derrota"
   Target_ru_ru "Поражение"
   Target_pt_br "Grande derrota"
   Target_uk_ua "Поразка"
   Modified 1625890527
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{60BA843705762142}" {
   Id "PS-ObjectiveLevel_MajorVictory"
   Target_en_us "Major victory"
   Target_es_es "Gran victoria"
   Target_ru_ru "Победа"
   Target_pt_br "Grande vitória"
   Target_uk_ua "Перемога"
   Modified 1625890554
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{60BA8437AF9DA0F3}" {
   Id "PS-ObjectiveLevel_MinorLoss"
   Target_en_us "Minor defeat"
   Target_es_es "Derrota menor"
   Target_ru_ru "Незначительное поражение"
   Target_pt_br "Derrota menor"
   Target_uk_ua "Мала поразка"
   Modified 1625890853
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{60BA84377297495A}" {
   Id "PS-ObjectiveLevel_MinorVictory"
   Target_en_us "Minor victory"
   Target_es_es "Victoria menor"
   Target_ru_ru "Незначительная победа"
   Target_pt_br "Vitória menor"
   Target_uk_ua "Мала перемога"
   Modified 1625890480
   Author "zazul"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EBE323E513FFB52}" {
   Id "PS-ObserverPlayersList"
   Target_en_us "Alive players"
   Target_es_es "Jugadores vivos"
   Target_ru_ru "Живые игроки"
   Target_pt_br "Jogadores vivos"
   Target_uk_ua "Живі гравці"
   Modified 1625888854
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EBE323E40F74A24}" {
   Id "PS-Preview_PleaseWait"
   Target_en_us "Please wait"\
   "Game will start soon"
   Target_es_es "Por favor espera"\
   "La partida comenzara pronto"
   Target_ru_ru "Пожалуйста подождите"\
   "Игра скоро начнётся"
   Target_pt_br "Por favor espere"\
   "A partida começara logo"
   Target_uk_ua "Будь ласка зачекайте Гра скоро почнеться"
   Modified 1625888845
   Author "zazul"
   LastChanged "class"
  }
  CustomStringTableItem "{5EC5311F409ED937}" {
   Id "PS-Spectator_SwitchSpectatorUI"
   Target_en_us "Hide/Show UI"
   Target_es_es "Ocultar/Mostrar UI"
   Target_ru_ru "Скрыть/Показать UI"
   Target_pt_br "Ocultar/Mostrar UI"
   Target_uk_ua "Сховати/Показати UI"
   Modified 1625888770
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EB6E12BC67891C4}" {
   Id "PS-VoNRoom_Command"
   Target_en_us "HQ"
   Target_es_es "Mando"
   Target_ru_ru "Штаб"
   Target_pt_br "Comando"
   Target_uk_ua "Штаб"
   Modified 1625888720
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EB6E12BC05F7F27}" {
   Id "PS-VoNRoom_Faction"
   Target_en_us "Faction"
   Target_es_es "Bando"
   Target_ru_ru "Фракция"
   Target_pt_br "Facção"
   Target_uk_ua "Фракція"
   Modified 1625888717
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EB6E12BF9F8C213}" {
   Id "PS-VoNRoom_Global"
   Target_en_us "Global"
   Target_es_es "Global"
   Target_ru_ru "Глобальный"
   Target_pt_br "Global"
   Target_uk_ua "Глобальний"
   Modified 1625888688
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5EB6FE5384337A16}" {
   Id "PS-VoNRoom_Header"
   Target_en_us "Voice сhannels"
   Target_es_es "Canales de voz"
   Target_ru_ru "Голосовые каналы"
   Target_pt_br "Canal de voz"
   Target_uk_ua "Голосові канали"
   Modified 1625888668
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0C9CB1CF9CE91D}" {
   Id "PS-VoNRoom_Local"
   Target_en_us "Deafen"
   Target_es_es "Silenciar"
   Target_ru_ru "Откл.звук"
   Target_pt_br "Silenciar"
   Target_uk_ua "Вимк.звук"
   Modified 1625888656
   Author "SeskPC"
   LastChanged "class"
  }
  CustomStringTableItem "{5F0C9CB1EFDDDB2E}" {
   Id "PS-VoNRoom_Public"
   Target_en_us "public channel"
   Target_es_es "canal publico"
   Target_ru_ru "публичный канал"
   Target_pt_br "canal publico"
   Target_uk_ua "публичний канал"
   Modified 1625888582
   Author "SeskPC"
   LastChanged "class"
  }
 }
}