StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5EB30CD4368261A7}" {
   Id "PS-GameMaster_PlayableGroup"
   Target_en_us "Playable Unit"
   Target_ru_ru "Играбельный Чел"
   Modified 1588796631
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE506E004252}" {
   Id "PS-GameModeHeader_Advance"
   Target_en_us "Advance"
   Target_ru_ru "Далее"
   Modified 1589052626
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE5226347A67}" {
   Id "PS-GameModeHeader_Briefing"
   Target_en_us "Briefing"
   Target_ru_ru "Инструктаж"
   Modified 1589051957
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE52166ABC2A}" {
   Id "PS-GameModeHeader_Debriefing"
   Target_en_us "Debriefing"
   Target_ru_ru "Итоги"
   Modified 1589051905
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE523BA20242}" {
   Id "PS-GameModeHeader_InGame"
   Target_en_us "Game"
   Target_ru_ru "Игра"
   Modified 1589054432
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE5256808E8E}" {
   Id "PS-GameModeHeader_Lobby"
   Target_en_us "Lobby"
   Target_ru_ru "Лобби"
   Modified 1589051783
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE52778D1F25}" {
   Id "PS-GameModeHeader_Preview"
   Target_en_us "Mission Preview"
   Target_ru_ru "Предпросмотр"
   Modified 1589052651
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF40044FB3}" {
   Id "PS-Keybind_Comms_Playable_Selector"
   Target_en_us "Team switch"
   Target_ru_ru "Смена роли"
   Modified 1588028307
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932C446D469ED}" {
   Id "PS-Keybind_CommsOpenLobby"
   Target_en_us "Open lobby"
   Target_ru_ru "Открыть лобби"
   Modified 1588200867
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941A166E74B}" {
   Id "PS-Lobby_Chat"
   Target_en_us "Chat"
   Target_ru_ru "Чат"
   Modified 1588026348
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF442B2167}" {
   Id "PS-Lobby_Factions"
   Target_en_us "Factions"
   Target_ru_ru "Фракции"
   Modified 1588025331
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932EC5F220341}" {
   Id "PS-Lobby_ForceStart"
   Target_en_us "Start game"
   Target_ru_ru "Начать игру"
   Modified 1588355597
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932EA0659A8C5}" {
   Id "PS-Lobby_Join"
   Target_en_us "Join game"
   Target_ru_ru "Вступить в игру"
   Modified 1588149476
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA932E9950F27EF}" {
   Id "PS-Lobby_JoinAsObserver"
   Target_en_us "Spectate"
   Target_ru_ru "Наблюдать"
   Modified 1588150413
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF46DC78AF}" {
   Id "PS-Lobby_LoadoutPreview"
   Target_en_us "Loadout Preview"
   Target_ru_ru "Предпросмотр"
   Modified 1588025334
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EAEBB2F34252729}" {
   Id "PS-Lobby_OpenMenu"
   Target_en_us "Open menu"
   Target_ru_ru "Открыть меню"
   Modified 1588510988
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF798A6D5B}" {
   Id "PS-Lobby_Players"
   Target_en_us "Players"
   Target_ru_ru "Игроки"
   Modified 1588025336
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941AE8846DA}" {
   Id "PS-Lobby_Ready"
   Target_en_us "Ready"
   Target_ru_ru "Готов"
   Modified 1588026052
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF7D6EDF21}" {
   Id "PS-Lobby_Roles"
   Target_en_us "Roles"
   Target_ru_ru "Роли"
   Modified 1588025338
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6E12BC67891C4}" {
   Id "PS-VoNRoom_Command"
   Target_en_us "HQ"
   Target_ru_ru "Штаб"
   Modified 1589044359
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6E12BC05F7F27}" {
   Id "PS-VoNRoom_Faction"
   Target_en_us "Faction"
   Target_ru_ru "Фракция"
   Modified 1589044327
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6E12BF9F8C213}" {
   Id "PS-VoNRoom_Global"
   Target_en_us "Global"
   Target_ru_ru "Глобальный"
   Modified 1589044312
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EB6FE5384337A16}" {
   Id "PS-VoNRoom_Header"
   Target_en_us "Voice Channels"
   Target_ru_ru "Голосовые Каналы"
   Modified 1589051689
   Author "SeskPC"
   LastChanged "SeskPC"
  }
 }
}