StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5EA73DBF40044FB3}" {
   Id "PS-Keybind_Comms_Playable_Selector"
   Target_en_us "Team switch"
   Target_ru_ru "Смена роли"
   Modified 1588028307
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941A166E74B}" {
   Id "PS-Lobby_Chat"
   Target_en_us "Chat"
   Target_ru_ru "Чат"
   Modified 1588026348
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941A71E17E8}" {
   Id "PS-Lobby_CloseLobby"
   Target_en_us "Leave game"
   Target_ru_ru "Покинуть игру"
   Modified 1588026309
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF442B2167}" {
   Id "PS-Lobby_Factions"
   Target_en_us "Factions"
   Target_ru_ru "Фракции"
   Modified 1588025331
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF46DC78AF}" {
   Id "PS-Lobby_LoadoutPreview"
   Target_en_us "Loadout Preview"
   Target_ru_ru "Предпросмотр"
   Modified 1588025334
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF798A6D5B}" {
   Id "PS-Lobby_Players"
   Target_en_us "Players"
   Target_ru_ru "Игроки"
   Modified 1588025336
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA75941AE8846DA}" {
   Id "PS-Lobby_Ready"
   Target_en_us "Ready"
   Target_ru_ru "Готов"
   Modified 1588026052
   Author "SeskPC"
   LastChanged "SeskPC"
  }
  CustomStringTableItem "{5EA73DBF7D6EDF21}" {
   Id "PS-Lobby_Roles"
   Target_en_us "Roles"
   Target_ru_ru "Роли"
   Modified 1588025338
   Author "SeskPC"
   LastChanged "SeskPC"
  }
 }
}