SCR_MissionHeader {
 World "{CA75436A3C860FB9}Worlds/ArlandLobby/ArlandLobby.ent"
 m_sName "Arland Lobby"
 m_sAuthor "Ram and Sesk"
 m_sPath "Missions/ArlandLobby.conf"
 m_sDescription "Everon with Reforger Lobby"
 m_sDetails "Everon with Reforger Lobby"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "Lobby"
 m_iPlayerCount 128
}